# Generated by Django 4.1.7 on 2023-06-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_actor_surname_alter_director_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='country',
            field=models.CharField(default='не указана', max_length=150, verbose_name='Страна'),
        ),
    ]
