# Generated by Django 4.1.7 on 2023-06-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_film_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='slug',
            field=models.SlugField(max_length=150, null=True, unique=True),
        ),
    ]
