# Generated by Django 4.1.7 on 2023-03-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='films',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AddField(
            model_name='films',
            name='genre',
            field=models.CharField(default='', max_length=50, verbose_name='Жанр'),
        ),
    ]
